name: Re-build on jackson-databind push
on:
  repository_dispatch:
    types: [jackson-databind-pushed]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Do we want wide matrix build? For now, limited
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      matrix:
        # 03-Jun-2024, tatu: Apparently Scala won't like JDK 21
        java_version: ['8', '11', '17']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: 2.x
    - name: Set up JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp clean verify
