name: Re-build on jackson-databind 2.x push
on:
  repository_dispatch:
    types: [jackson-databind-pushed]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Do we want wide matrix build? For now, limited
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      matrix:
        # 03-Jun-2024, tatu: Apparently Scala won't like JDK 21
        java_version: ['8', '11', '17']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: 2.x
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp clean verify
