name: Re-build on jackson-databind 2.x push
on:
  repository_dispatch:
    types: [jackson-databind-pushed]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Do we want wide matrix build? For now, limited
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      matrix:
        # 03-Jun-2024, tatu: Apparently Scala won't like JDK 21
        java_version: ['8', '11', '17']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: 2.x
    - name: Set up JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp clean verify
