name: Build and Run Tests
on:
  push:
    branches: [2.*]
  pull_request:
    branches: [2.*]
  # Also run once per day anyway, at 10:00 UTC (18:00 PT)
  schedule:
    - cron: "0 10 * * *"
permissions:
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      matrix:
        # JDK 21 fails for Scala module for some reason
        java_version: ['8', '11', '17']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      run: ./mvnw -V -B -ff -ntp verify
